# This file was generated by GoReleaser. DO NOT EDIT.
cask "rift" do
  name "rift"
  desc "Instant, copy-on-write database branches for Postgres"
  homepage "https://riftdata.io"
  version "0.0.35"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rift"

  on_macos do
    on_intel do
      url "https://github.com/riftdata/rift/releases/download/v#{version}/rift_#{version}_darwin_amd64.tar.gz"
      sha256 "aafc23c69ce6f71855c0e48e22f9430d1c91256140f36e4c1df2c7d1a51c4661"
    end
    on_arm do
      url "https://github.com/riftdata/rift/releases/download/v#{version}/rift_#{version}_darwin_arm64.tar.gz"
      sha256 "aadc78be465fa53843598267b127790de9c5e401dd3f5791adcd94882c3d5f3a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/riftdata/rift/releases/download/v#{version}/rift_#{version}_linux_amd64.tar.gz"
      sha256 "d31cd275c82d8d6915b623ff01ce4ca8ea389b85099517cdf7b504c3446d1a2c"
    end
    on_arm do
      url "https://github.com/riftdata/rift/releases/download/v#{version}/rift_#{version}_linux_arm64.tar.gz"
      sha256 "7fa4a8ca4bc767c6f28d66448d6ea84a8bf0e8ff84598b787d4d75bde955f225"
    end
  end

  # No zap stanza required
end
