# This file was generated by GoReleaser. DO NOT EDIT.
cask "rift" do
  name "rift"
  desc "Instant, copy-on-write database branches for Postgres"
  homepage "https://riftdata.io"
  version "0.0.42"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rift"

  on_macos do
    on_intel do
      url "https://github.com/riftdata/rift/releases/download/v#{version}/rift_#{version}_darwin_amd64.tar.gz"
      sha256 "0ab72cfb5ba3469a6ecdb5ba259ba1d7cc4ada5bc502010f69f12eba891202ce"
    end
    on_arm do
      url "https://github.com/riftdata/rift/releases/download/v#{version}/rift_#{version}_darwin_arm64.tar.gz"
      sha256 "421aa91ea0c4f9da6537f50a4f942d5464a8cf141987c35afa180f1df87dd4d4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/riftdata/rift/releases/download/v#{version}/rift_#{version}_linux_amd64.tar.gz"
      sha256 "b842f2bcd6d9627381a9b8cbdf4b5d5a27a3431f9befee36d8a3aa0f853354ae"
    end
    on_arm do
      url "https://github.com/riftdata/rift/releases/download/v#{version}/rift_#{version}_linux_arm64.tar.gz"
      sha256 "d9b3c6ec8dddb9e4fa5f668ae8ad3f1d2f5a1cc5053efd065ff46780f5b3e90d"
    end
  end

  # No zap stanza required
end
